### ISSUE TITLE
certaines watchlist n'ont pas d'attribut owner, ce qui cause un problème si on veut chercher son owner par son id

### ISSUE THREAD

**Issue by franclml** [GLO3102/UMovie#10]
{
    "name": "juju",
    "movies": [],
    "id": "5668a1c1c4730803004104d5"
  },

 {
    "name": "police movie",
    "movies": [],
    "id": "56689443aa5435030007a88f"
  }

**Comment by wfortin** [comment]
Ces playlist ont-elles été créés avec l'API /unsecure ? si oui il est normal qu'il n'aient pas d'owner. Supprime ces watchlists et utilise seulement ceux créés avec un user authentifié.
