### ISSUE TITLE
Pull request ?

### ISSUE THREAD

**Issue by mapy69003** [GLO3102/UMovie#114]
@vseguin ,

As you said in a previous Issue :

![image](https://cloud.githubusercontent.com/assets/6999772/24221384/81eddac6-0f24-11e7-92d9-70ddfddb8107.png)

But I just can't push a commit because

![image](https://cloud.githubusercontent.com/assets/6999772/24221534/0796d2e0-0f25-11e7-93b5-46864a19d72c.png)

Could you fix this for me please ?

**Comment by vseguin** [comment]
@wfortin any idea there?

**Comment by wfortin** [comment]
You need to first "fork" the repo, then apply your changes to your repo, then, submit a PR.
