### ISSUE TITLE
Crash API follow user

### ISSUE THREAD

**Issue by PavoneM** [GLO3102/UMovie#12]
L'API semble crasher si on envois un data vide dans la requête pour follow un utilisateur.

```
       $.ajax({
            url: URL + '/follow',
            type: 'POST',
            data: {},
            dataType: "json",
            contentType: 'application/json'
        })
```

**Comment by subneo23** [comment]
Je confirme, en lui passant un undefined, elle crash aussi pendant un bon 5-10 minutes

**Comment by vseguin** [comment]
PRs welcome :)

**Comment by kedzilla** [comment]
Les modifs ont été apportées ici je pense déjà!

https://github.com/GLO3102/UMovie/pull/118
