### ISSUE TITLE
Routing - Naming inconsistencies

### ISSUE THREAD

**Issue by jumojer** [GLO3102/UMovie#13]
I noticed that for tv shows the routes are `/tvshows/season/:id` and `/tvshows/season/:id/episodes`.

In those routes, I think "season" should be changed to plural for consistency. Especially considering that the search url is `/search/tvshows/seasons` (notice the plural) and that all other ressource urls are also plural.

That would, also, allow for easier crafting of the search url for a model as it all search urls would be consistant with `'search/'+model.urlRoot`.

**Comment by vseguin** [comment]
PR vas merged.

**Comment by vseguin** [comment]
PR merged.
