### ISSUE TITLE
création de watchlist n'insère pas le name de la watchlist

### ISSUE THREAD

**Issue by franclml** [GLO3102/UMovie#9]
{
    "movies": [],
    "owner": {
      "email": "fra123@mail.com",
      "name": "fra123",
      "id": "56689a57c4730803004104d0"
    },
    "id": "56689ab3c4730803004104d1"
  }

**Comment by franclml** [comment]
avec un post sur https://umovie.herokuapp.com/watchlists et un body:
{
"name": "frafra"
}

**Comment by wfortin** [comment]
Ça fonctionne ici:

![image](https://cloud.githubusercontent.com/assets/2165256/11702948/ecb0b5ba-9ea8-11e5-8792-39c21d315c90.png)
